services:
  - type: web
    name: tarea-bienvenida
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
